import type { BoardProfile } from './board-profile.js'

const crowpanel28: BoardProfile = {
  boardId: 'crowpanel_28',
  boardName: 'Elecrow CrowPanel 2.8" ESP32',
  chipFamily: 'esp32',
  lcd: {
    driver: 'ili9341',
    pinMosi: 13,
    pinMiso: 12,
    pinSclk: 14,
    pinCs: 15,
    pinDc: 2,
    pinRst: -1,
    pinBl: 27,
    freqWriteHz: 27_000_000,
    panelWidth: 240,
    panelHeight: 320,
    memoryWidth: 240,
    memoryHeight: 320,
    defaultRotation: 3,
    rgbOrderBgr: false,
    invert: false,
    busSharedWithTouch: true,
    readable: false,
    colorDepth: 16,
  },
  backlight: { present: true, pwmChannel: 0, pwmFreqHz: 5_000, defaultDuty: 200, invert: false },
  touch: {
    driver: 'xpt2046',
    pinCs: 33,
    pinIrq: -1,
    freqHz: 2_500_000,
    needsCalibration: true,
    pinSda: -1,
    pinScl: -1,
  },
  can: { controller: 'esp_twai', pinTx: 25, pinRx: 32, defaultSpeedKbps: 500 },
  storage: { spiffsPresent: true, spiffsSizeKb: 1024, sdPresent: false, sdPinCs: -1 },
  conn: { wifiSupported: true, bleSupported: true, psramPresent: false },
}

const genericIli9341: BoardProfile = {
  boardId: 'generic_ili9341',
  boardName: 'Generic ESP32 + ILI9341 320x240 + XPT2046',
  chipFamily: 'esp32',
  lcd: {
    driver: 'ili9341',
    pinMosi: 23,
    pinMiso: 19,
    pinSclk: 18,
    pinCs: 5,
    pinDc: 2,
    pinRst: 4,
    pinBl: 15,
    freqWriteHz: 27_000_000,
    panelWidth: 240,
    panelHeight: 320,
    memoryWidth: 240,
    memoryHeight: 320,
    defaultRotation: 3,
    rgbOrderBgr: false,
    invert: false,
    busSharedWithTouch: true,
    readable: false,
    colorDepth: 16,
  },
  backlight: { present: true, pwmChannel: 0, pwmFreqHz: 5_000, defaultDuty: 200, invert: false },
  touch: {
    driver: 'xpt2046',
    pinCs: 21,
    pinIrq: 27,
    freqHz: 2_500_000,
    needsCalibration: true,
    pinSda: -1,
    pinScl: -1,
  },
  can: { controller: 'esp_twai', pinTx: 25, pinRx: 32, defaultSpeedKbps: 500 },
  storage: { spiffsPresent: true, spiffsSizeKb: 1024, sdPresent: false, sdPinCs: -1 },
  conn: { wifiSupported: true, bleSupported: true, psramPresent: false },
}

const genericIli9341Gt911: BoardProfile = {
  boardId: 'generic_ili9341_gt911',
  boardName: 'Generic ESP32 + ILI9341 320x240 + GT911 capacitive',
  chipFamily: 'esp32',
  lcd: {
    driver: 'ili9341',
    pinMosi: 23,
    pinMiso: 19,
    pinSclk: 18,
    pinCs: 5,
    pinDc: 2,
    pinRst: 4,
    pinBl: 15,
    freqWriteHz: 27_000_000,
    panelWidth: 240,
    panelHeight: 320,
    memoryWidth: 240,
    memoryHeight: 320,
    defaultRotation: 3,
    rgbOrderBgr: false,
    invert: false,
    busSharedWithTouch: false,
    readable: false,
    colorDepth: 16,
  },
  backlight: { present: true, pwmChannel: 0, pwmFreqHz: 5_000, defaultDuty: 200, invert: false },
  touch: {
    driver: 'gt911',
    pinCs: -1,
    pinIrq: 27,
    freqHz: 400_000,
    needsCalibration: false,
    pinSda: 21,
    pinScl: 22,
  },
  can: { controller: 'esp_twai', pinTx: 25, pinRx: 32, defaultSpeedKbps: 500 },
  storage: { spiffsPresent: true, spiffsSizeKb: 1024, sdPresent: false, sdPinCs: -1 },
  conn: { wifiSupported: true, bleSupported: true, psramPresent: false },
}

const waveshareS328: BoardProfile = {
  boardId: 'waveshare_s3_28',
  boardName: 'Waveshare ESP32-S3 2.8" ST7789T3 + CST816',
  chipFamily: 'esp32s3',
  lcd: {
    driver: 'st7789',
    pinMosi: -1,
    pinMiso: -1,
    pinSclk: -1,
    pinCs: -1,
    pinDc: -1,
    pinRst: -1,
    pinBl: -1,
    freqWriteHz: 40_000_000,
    panelWidth: 240,
    panelHeight: 320,
    memoryWidth: 240,
    memoryHeight: 320,
    defaultRotation: 0,
    rgbOrderBgr: false,
    invert: true,
    busSharedWithTouch: false,
    readable: false,
    colorDepth: 16,
  },
  backlight: { present: true, pwmChannel: 0, pwmFreqHz: 5_000, defaultDuty: 200, invert: false },
  touch: {
    driver: 'cst816s',
    pinCs: -1,
    pinIrq: -1,
    freqHz: 400_000,
    needsCalibration: false,
    pinSda: -1,
    pinScl: -1,
  },
  can: { controller: 'esp_twai', pinTx: -1, pinRx: -1, defaultSpeedKbps: 500 },
  storage: { spiffsPresent: true, spiffsSizeKb: 1024, sdPresent: false, sdPinCs: -1 },
  conn: { wifiSupported: true, bleSupported: true, psramPresent: true },
}

export const BOARD_PROFILES: readonly BoardProfile[] = [
  crowpanel28,
  genericIli9341,
  genericIli9341Gt911,
  waveshareS328,
]

export const getBoardProfile = (boardId: string): BoardProfile | undefined =>
  BOARD_PROFILES.find((profile) => profile.boardId === boardId)
