// ecu-profiles/index.ts — Built-in ECU signal profiles

import type { SignalDef } from '../types/signal'

export interface EcuProfile {
  id: string
  name: string
  description: string
  /** Value written to SignalConfig.protocol on export */
  protocol: string
  signals: SignalDef[]
}

const MAXXECU_STREET_SIGNALS: SignalDef[] = [
  {
    name: 'rpm',
    canFrameId: '0x370',
    startByte: 0,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: 'rpm',
    min: 0,
    max: 10000,
    timeoutMs: 500,
  },
  {
    name: 'throttle_pos',
    canFrameId: '0x370',
    startByte: 2,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 0.5,
    offset: 0.0,
    unit: '%',
    min: 0,
    max: 100,
    timeoutMs: 500,
  },
  {
    name: 'map_kpa',
    canFrameId: '0x370',
    startByte: 3,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.1,
    offset: 0.0,
    unit: 'kPa',
    min: 0,
    max: 400,
    timeoutMs: 500,
  },
  {
    name: 'iat_c',
    canFrameId: '0x370',
    startByte: 5,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: -40,
    unit: '°C',
    min: -40,
    max: 215,
    timeoutMs: 1000,
  },
  {
    name: 'speed_kph',
    canFrameId: '0x370',
    startByte: 6,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.1,
    offset: 0.0,
    unit: 'km/h',
    min: 0,
    max: 300,
    timeoutMs: 500,
  },
  {
    name: 'lambda_1',
    canFrameId: '0x371',
    startByte: 0,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.001,
    offset: 0.0,
    unit: 'λ',
    min: 0.5,
    max: 2.0,
    timeoutMs: 500,
  },
  {
    name: 'gear',
    canFrameId: '0x371',
    startByte: 2,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: '',
    min: 0,
    max: 6,
    timeoutMs: 500,
  },
  {
    name: 'fuel_press_bar',
    canFrameId: '0x371',
    startByte: 3,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.01,
    offset: 0.0,
    unit: 'bar',
    min: 0,
    max: 10,
    timeoutMs: 1000,
  },
  {
    name: 'coolant_temp_c',
    canFrameId: '0x372',
    startByte: 0,
    byteLength: 2,
    bigEndian: true,
    signed: true,
    scale: 0.1,
    offset: -40,
    unit: '°C',
    min: -40,
    max: 150,
    timeoutMs: 1000,
  },
  {
    name: 'oil_temp_c',
    canFrameId: '0x372',
    startByte: 2,
    byteLength: 2,
    bigEndian: true,
    signed: true,
    scale: 0.1,
    offset: -40,
    unit: '°C',
    min: -40,
    max: 180,
    timeoutMs: 1000,
  },
  {
    name: 'oil_press_bar',
    canFrameId: '0x372',
    startByte: 4,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.01,
    offset: 0.0,
    unit: 'bar',
    min: 0,
    max: 10,
    timeoutMs: 1000,
  },
  {
    name: 'battery_volts',
    canFrameId: '0x373',
    startByte: 0,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.01,
    offset: 0.0,
    unit: 'V',
    min: 8,
    max: 18,
    timeoutMs: 2000,
  },
  {
    name: 'flag_mil',
    canFrameId: '0x374',
    startByte: 0,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: '',
    min: 0,
    max: 1,
    timeoutMs: 2000,
    bitMask: '0x01',
  },
  {
    name: 'flag_launch_ctrl',
    canFrameId: '0x374',
    startByte: 0,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: '',
    min: 0,
    max: 1,
    timeoutMs: 2000,
    bitMask: '0x02',
  },
  {
    name: 'map_number',
    canFrameId: '0x375',
    startByte: 0,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: '',
    min: 1,
    max: 16,
    timeoutMs: 5000,
  },
  {
    name: 'afr_1',
    canFrameId: '0x371',
    startByte: 4,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.001,
    offset: 0.0,
    unit: 'AFR',
    min: 7.0,
    max: 20.0,
    timeoutMs: 500,
  },
  {
    name: 'boost_bar',
    canFrameId: '0x370',
    startByte: 3,
    byteLength: 2,
    bigEndian: true,
    signed: true,
    scale: 0.01,
    offset: -1.0,
    unit: 'bar',
    min: -1.0,
    max: 3.0,
    timeoutMs: 500,
  },
]

export const ECU_PROFILES: EcuProfile[] = [
  {
    id: 'maxxecu-street',
    name: 'MaxxECU Street',
    description: 'MaxxECU Street/Race CAN broadcast layout (firmware default)',
    protocol: 'maxxecu_v1.2',
    signals: MAXXECU_STREET_SIGNALS,
  },
  {
    id: 'generic-blank',
    name: 'Generic (blank)',
    description: "Empty template — fill in from your ECU's CAN documentation",
    protocol: 'generic',
    signals: [],
  },
]

export const DEFAULT_PROFILE_ID = 'maxxecu-street' as const
