import type { SignalDef } from '../schemas/signal.js'
import type { EcuProfile } from './types.js'

const OBDII_SIGNALS: SignalDef[] = [
  {
    name: 'rpm',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.25,
    offset: 0.0,
    unit: 'rpm',
    min: 0,
    max: 8000,
    warningLevel: 6500,
    dangerLevel: 7200,
    timeoutMs: 2000,
  },
  {
    name: 'speed_kph',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: 0.0,
    unit: 'km/h',
    min: 0,
    max: 300,
    timeoutMs: 2000,
  },
  {
    name: 'coolant_temp_c',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: -40.0,
    unit: '°C',
    min: -40,
    max: 150,
    warningLevel: 100,
    dangerLevel: 115,
    timeoutMs: 2000,
  },
  {
    name: 'throttle_pos',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 100 / 255,
    offset: 0.0,
    unit: '%',
    min: 0,
    max: 100,
    timeoutMs: 2000,
  },
  {
    name: 'iat_c',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 1,
    bigEndian: true,
    signed: false,
    scale: 1.0,
    offset: -40.0,
    unit: '°C',
    min: -40,
    max: 100,
    timeoutMs: 2000,
  },
  {
    name: 'battery_volts',
    canFrameId: '0x7E8',
    startByte: 3,
    byteLength: 2,
    bigEndian: true,
    signed: false,
    scale: 0.001,
    offset: 0.0,
    unit: 'V',
    min: 8,
    max: 18,
    warningLevel: 12.0,
    dangerLevel: 11.5,
    timeoutMs: 5000,
  },
]

export const OBD2_J1979_PROFILE: EcuProfile = {
  id: 'obd2-j1979',
  name: 'OBD-II (J1979 PIDs)',
  description:
    'Standard OBD-II PIDs (RPM, speed, coolant, TPS, IAT, battery) at the J1979 response frame 0x7E8. Requires firmware polling support (issue #841) — until that ships these signals stay silent on a passive bus.',
  protocol: 'obd2_j1979',
  signals: OBDII_SIGNALS,
}
